language: go
go: "1.10"

env:
  - DEP_VERSION="0.4.1"

before_install:
  # gox simplifies building for multiple architectures
  - go get github.com/mitchellh/gox
  # Download the binary to bin folder in $GOPATH
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  # Make the binary executable
  - chmod +x $GOPATH/bin/dep

install:
  - # skip

script:
  #- go get -t -v ./...
  #- diff -u <(echo -n) <(gofmt -d .)
  #- go vet $(go list ./... | grep -v /vendor/)
  #- go test -v -race ./...
  # Only build binaries from the latest Go release.
  - dep ensure
  - gox -os="linux darwin windows" -arch="amd64" -output="logshare.." -ldflags "-X main.Rev=`git rev-parse --short HEAD`" -verbose ./...;

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    # Your *encrypted* GitHub key, as the output of the Travis CI CLI tool.
    secure: UfNHWAeaITUWDeM5313BruYjGhwFFI19Wzr1DWkr659y8FcX3F1IVoPg006SyzRLnX7Y93dQuSmHmCW3+wIJVPj32piXITZZ7x+3spDA24QOOPDqCyByg4qgykHf1h50woRTk3TFRlEVFu2lchbZ78JcWAHUQTXIKv9r1aarV0Cjjtun3UnG76OuNsItO7OnLPacriUn26RwWpqJzTFJgU0D2eIbVjOjucNINantlDRVwd8ujh9FYylop20s+obdmG/AcRm1GGmgCYUK1WsXG84zJSBQSnzliUEAf1fLj9YXeoV6UoyG4oFZthXEfMzzZg9sxvAbjp0WH7HoRC+EYkzKS2le7ZtzXmOoRXhkPt5ngetCxxmzLEj+b+wkdVgtPXfOnb102D3A33lHsEf9NYuzuYBdtGmLrh3Y95WscSj1guGPt3mxvjWJVflpzQcUOKnkQAcle9FUphBJ4CjrHh+fQN9US6YiDMGZuQrL8GxLhfDeoZsaSu1g/LyLHleknJzw8mM04HOadhVrUuX4D0E2xgrvd4OQ6mTXWmqGuBoISAkNTJYU/Sb4eghKELRaEYrMX48JkuNOQJQcDhTpe7Q9XNUlWxAXV4PO5U1hj2WqCQo3UDHi333vJYrc+3L5SVG+1n/yQcGO3ZW7LiXdPMLkDKxussciId/EKuUcixo=
  file:
  # The names of the binaries to output, based on the -output template passed to gox.
  - logshare.windows.amd64.exe
  - logshare.darwin.amd64
  - logshare.linux.amd64
  on:
    # What to repository to build
    repo: lagoon-platform/cli
    # Only build binaries for tagged commits
    tags: true
    
